-- TB_CLIENTE
INSERT INTO TB_CLIENTE (TIPO_PESSOA, CPF_CNPJ, NOME_RAZAO_SOCIAL, SITUACAO) VALUES ('PF', '12345678910', 'Cliente 1', 'ATIVO');

-- TB_PRODUTO
INSERT INTO TB_PRODUTO (NOME, VALOR, SITUACAO) VALUES ('Produto 1', 100, 'ATIVO');