-- TB_CLIENTE
INSERT INTO TB_CLIENTE (TIPO_PESSOA, NOME, CPF, SITUACAO) VALUES ('PF', 'Cliente 1', '12345678910', 'ATIVO');

-- TB_PRODUTO
INSERT INTO TB_PRODUTO (NOME, VALOR, SITUACAO) VALUES ('Produto 1', 100, 'ATIVO');